/**
 * Constants representing all standard SMTP response codes.
 * Each constant is named as `SMTP_<code>_<UPPERCASE_DESCRIPTION>` with the numeric value being the SMTP code.
 * Based on RFC 5321 and common extensions from Wikipedia's list of SMTP server return codes.
 * Note: Some codes may have multiple possible meanings; the description here is the primary or most common one.
 *
 * Usage:
 * import { SMTP_214_HELPMESSAGE } from './response-codes';
 *
 * Or import the entire object:
 * import smtpResponseCodes from './response-codes';
 * const { SMTP_214_HELPMESSAGE } = smtpResponseCodes;
 */
const SMTP_RESPONSE_CODES = {
	SMTP_211_SYSTEMSTATUSORHELPREPLY: 211,
	SMTP_214_HELPMESSAGE: 214,
	SMTP_220_SERVICEREADY: 220,
	SMTP_221_SERVICECLOSINGTRANSMISSIONCHANNEL: 221,
	SMTP_235_AUTHENTICATIONSUCCEEDED: 235,
	SMTP_240_QUIT: 240,
	SMTP_250_REQUESTEDMAILACTIONOKAYCOMPLETED: 250,
	SMTP_251_USERNOTLOCALWILLFORWARD: 251,
	SMTP_252_CANNOTVADUSERBUTWILLTRYTODELIVER: 252,

	SMTP_334_SERVERCHALLENGEBASE64: 334,
	SMTP_354_STARTMAILINPUT: 354,

	SMTP_421_SERVICENOTAVAILABLECLOSINGCHANNEL: 421,
	SMTP_432_PASSWORDTRANSITIONNEEDED: 432,
	SMTP_450_MAILBOXUNAVAILABLE: 450,
	SMTP_451_REQUESTEDACTIONABORTEDLOCALERROR: 451,
	SMTP_452_INSUFFICIENTSYSTEMSTORAGE: 452,
	SMTP_454_TEMPORARYAUTHENTICATIONFAILURE: 454,
	SMTP_455_SERVERUNABLETOACCOMMODATEPARAMETERS: 455,

	SMTP_500_SYNTAXERRORCOMMANDUNRECOGNIZED: 500,
	SMTP_501_SYNTAXERRORINPARAMETERSORARGUMENTS: 501,
	SMTP_502_COMMANDNOTIMPLEMENTED: 502,
	SMTP_503_BADSEQUENCEOFCOMMANDS: 503,
	SMTP_504_COMMANDPARAMETERNOTIMPLEMENTED: 504,
	SMTP_521_SERVERDOESNOTACCEPTMAIL: 521,
	SMTP_523_ENCRYPTIONNEEDED: 523,
	SMTP_530_AUTHENTICATIONREQUIRED: 530,
	SMTP_534_AUTHENTICATIONMECHANISMTOOWEAK: 534,
	SMTP_535_AUTHENTICATIONCREDENTIALSINVALID: 535,
	SMTP_538_ENCRYPTIONREQUIREDFORAUTHMECHANISM: 538,
	SMTP_550_MAILBOXUNAVAILABLE: 550,
	SMTP_551_USERNOTLOCALPLEASETTRY: 551,
	SMTP_552_EXCEEDEDSTORAGEALLOCATION: 552,
	SMTP_553_MAILBOXNAMENOTALLOWED: 553,
	SMTP_554_TRANSACTIONFAILED: 554,
	SMTP_556_DOMAINDOESNOTACCEPTMAIL: 556,
} as const;

export default SMTP_RESPONSE_CODES;

export const {
	SMTP_211_SYSTEMSTATUSORHELPREPLY,
	SMTP_214_HELPMESSAGE,
	SMTP_220_SERVICEREADY,
	SMTP_221_SERVICECLOSINGTRANSMISSIONCHANNEL,
	SMTP_235_AUTHENTICATIONSUCCEEDED,
	SMTP_240_QUIT,
	SMTP_250_REQUESTEDMAILACTIONOKAYCOMPLETED,
	SMTP_251_USERNOTLOCALWILLFORWARD,
	SMTP_252_CANNOTVADUSERBUTWILLTRYTODELIVER,

	SMTP_334_SERVERCHALLENGEBASE64,
	SMTP_354_STARTMAILINPUT,

	SMTP_421_SERVICENOTAVAILABLECLOSINGCHANNEL,
	SMTP_432_PASSWORDTRANSITIONNEEDED,
	SMTP_450_MAILBOXUNAVAILABLE,
	SMTP_451_REQUESTEDACTIONABORTEDLOCALERROR,
	SMTP_452_INSUFFICIENTSYSTEMSTORAGE,
	SMTP_454_TEMPORARYAUTHENTICATIONFAILURE,
	SMTP_455_SERVERUNABLETOACCOMMODATEPARAMETERS,

	SMTP_500_SYNTAXERRORCOMMANDUNRECOGNIZED,
	SMTP_501_SYNTAXERRORINPARAMETERSORARGUMENTS,
	SMTP_502_COMMANDNOTIMPLEMENTED,
	SMTP_503_BADSEQUENCEOFCOMMANDS,
	SMTP_504_COMMANDPARAMETERNOTIMPLEMENTED,
	SMTP_521_SERVERDOESNOTACCEPTMAIL,
	SMTP_523_ENCRYPTIONNEEDED,
	SMTP_530_AUTHENTICATIONREQUIRED,
	SMTP_534_AUTHENTICATIONMECHANISMTOOWEAK,
	SMTP_535_AUTHENTICATIONCREDENTIALSINVALID,
	SMTP_538_ENCRYPTIONREQUIREDFORAUTHMECHANISM,
	SMTP_550_MAILBOXUNAVAILABLE,
	SMTP_551_USERNOTLOCALPLEASETTRY,
	SMTP_552_EXCEEDEDSTORAGEALLOCATION,
	SMTP_553_MAILBOXNAMENOTALLOWED,
	SMTP_554_TRANSACTIONFAILED,
	SMTP_556_DOMAINDOESNOTACCEPTMAIL,
} = SMTP_RESPONSE_CODES;
