# Data directory
datadir = /var/mail/data

# Log directory
logdir = /var/log/mail

# certificate = /etc/ssl/private/mail/certificate.crt
# privatekey = /etc/ssl/private/mail/private.key

# host = 0.0.0.0
# port = 2525
# budget = auto
# timeout = 120

# default: 512KB
email_limit_size = 524288

# use PROXY v2 protocol connection support
proxy_support = false

# Write source IP address on header of message data
prepend_header_ip = true

# Record matching domain RCPT(s) on header of message data 
# The main purpose is to track spoofed RCPT that is omitted on message data
prepend_header_rcpt = true