# Data directory
datadir = /var/mail/data

# Log directory
logdir = /var/log/mail

# certificate = /etc/ssl/private/mail/certificate.crt
# privatekey = /etc/ssl/private/mail/private.key

# host = 0.0.0.0
# port = 2525
# budget = auto
# timeout = 120

# default: 512KB
email_limit_size = 524288

# To enable PROXY v2 connection header support
# proxy_support = true
# default: proxy_support = false