# Data directory
datadir = /var/mail/data

# Log directory
logdir = /var/log/mail

# certificate = /etc/ssl/private/mail/certificate.crt
# privatekey = /etc/ssl/private/mail/private.key

# host = 0.0.0.0
# port = 2525
# budget = auto
# timeout = 120

# default: 512KB
email_limit_size = 524288

# Enable PROXY v2 protocol connection support,
# Not enabled by default
# proxy_support = true

# Write source IP address on header of message data
prepend_header_ip = true